-- Таблица пользователей
create table users (
  id bigint generated by default as identity primary key,
  tg_id bigint unique not null,
  full_name text not null default '',
  phone text not null default '',
  inn text not null default '',
  balance bigint default 0,
  created_at timestamptz default now()
);

-- Таблица платежей (входящие)
create table payments (
  id bigint generated by default as identity primary key,
  user_tg_id bigint not null,
  amount bigint not null,
  method text not null,
  payer_phone text,
  created_at timestamptz default now()
);

-- Таблица расходов
create table expenses (
  id bigint generated by default as identity primary key,
  user_tg_id bigint not null,
  amount bigint not null,
  category text,
  receipt_url text,
  created_at timestamptz default now()
);

-- Индексы
create index idx_users_tg_id on users(tg_id);
create index idx_payments_user_tg_id on payments(user_tg_id);
create index idx_expenses_user_tg_id on expenses(user_tg_id);
